use_frameworks!
source 'https://github.com/PMComponent/PMSpace.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'

target 'PMAuthorKit_Example' do
  pod 'PMAuthorKit', :path => '../'

  target 'PMAuthorKit_Tests' do
    inherit! :search_paths

    
  end
end
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
        end
    end
end
